import fs from 'fs/promises';
import path from 'path';

// Get mode from command line arguments
const mode = process.argv[2];

if (!['sqlite', 'pg'].includes(mode)) {
  console.error('❌ Usage: npx tsx scripts/db-setup.ts [sqlite|pg]');
  process.exit(1);
}

const root = process.cwd();
const prismaDir = path.join(root, 'prisma');
const partsDir = path.join(prismaDir, 'parts');

async function main() {
  console.log(`🏗️  Assembling Prisma Schema for: ${mode.toUpperCase()}...`);

  const configFile = path.join(partsDir, `config.${mode}.prisma`);
  const modelsFile = path.join(partsDir, 'models.prisma');
  const outputFile = path.join(prismaDir, 'schema.prisma');

  try {
    const configContent = await fs.readFile(configFile, 'utf-8');
    const modelsContent = await fs.readFile(modelsFile, 'utf-8');

    // Add a warning header
    const header = `// ⚠️ AUTOGENERATED FILE. DO NOT EDIT MANUALLY.\n// ⚠️ Run 'pnpm db:switch:${mode}' to update.\n\n`;

    await fs.writeFile(outputFile, header + configContent + '\n' + modelsContent);
    console.log(`✅ prisma/schema.prisma created successfully!`);
    
    console.log(`\nNext steps:`);
    console.log(`1. Run 'npx prisma generate' to update the client.`);
    if (mode === 'sqlite') {
      console.log(`2. Run 'npx prisma db push' to create dev.db.`);
    }
  } catch (error) {
    console.error('❌ Error assembling schema:', error);
    process.exit(1);
  }
}

main();
